name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sreeramjvp/deploy-test:latest .

      - name: Push Docker image
        run: docker push sreeramjvp/deploy-test:latest

      - name: Run Docker container
        run: |
          docker stop my-script-container || true
          docker rm my-script-container || true
          docker run -d --name my-script-container sreeramjvp/deploy-test:latest
